### ISSUE TITLE
Litecoin Support

### ISSUE THREAD

**Issue by ottosuess** [LN-Zap/zap-iOS#1]
Currently we don't _really_ support LTC. We only use `Bitcoin` icons, only convert to BTC price, etc. I think it would be valuable if we supported Litecoin and allowed the user to pick which chain they'd like to launch on during onboarding.

**Comment by kcw-grunt** [comment]
joined the slack @ottosuess and in just need see how I should get started

**Comment by nspassov** [comment]
Digging up this question since I run a litecoin lnd node. It doesn't seem like any work was done on this yet, am I correct? I would like to help.

**Comment by ottosuess** [comment]
sorry, talked to everybody involved and this is not something we want to spend our time on right now.

just to keep the codebase as simple and focused as possible to make future development simpler.

but you can always fork and create a litecoin zap app 😉

**Comment by nspassov** [comment]
I have already forked the repo 😄 I actually run nodes in both currencies so I think it would be cool if the same codebase supports both (I saw this is the case in the desktop app). Let's see if I find enough time 😄
