### ISSUE TITLE
Indication which LND Wallet is currently connected.

### ISSUE THREAD

**Issue by AmazingDroopy** [LN-Zap/zap-iOS#102]
**Is your feature request related to a problem? Please describe.**
When connecting multiple LND nodes, you can switch, but you cannot see to which LND Wallet you are connected in the session you currently use.

**Describe the solution you'd like**
1. In the Wallet Tab there should be a mention of the Wallet you connect to.
2. In the Settings Tab, like in the lines for "Currency", "Block Explorer" you could show the currently connected Wallet in the line for "Manage Wallets" 

**Describe alternatives you've considered**
The Manage Wallets list also gives no indication to which wallet you are currently connected.

**Comment by ottosuess** [comment]
sounds good, i'll add that 🔥
