### ISSUE TITLE
Checking Remote capacity -> Closing Channel Popup window harder than Closing Channel.

### ISSUE THREAD

**Issue by AmazingDroopy** [LN-Zap/zap-iOS#103]
**Is your feature request related to a problem? Please describe.**
When checking the remote channel capacity that is available for invoicing, you cannot see Remote Capacity in the Channels overview, since that only shows the local capacity.

Entering the channel details does show the remote capacity, which is ok, but far away in the app.
When you viewed the details and need to close the popup window, the size of the "Close Channel" option is much bigger and easier to hit than closing the Popup window. This leads to choosing the wrong button 80% of the time and Closing the Channel is not the most wanted action when checking channel info.

**Describe the solution you'd like**
Option 1: Show the Remote Capacity of the channel like the local capacity in the Channel overview. This way you do not need to open details for info you need for quick reference.

Option 2: Anticipating AMP, show a total of Local- AND Remote Capacity on all active Channels on the Wallet Tab.

**Describe alternatives you've considered**
When opening the Receive option for Lightning, you might show the actual remote channel capacity available in active channels.

**Comment by ottosuess** [comment]
good point, we need to work on channel UI / UX
