### ISSUE TITLE
Zap should support norwegian kroner 🇳🇴

### ISSUE THREAD

**Issue by knutnyg** [LN-Zap/zap-iOS#106]
Zap should support showing balances and payments in NOK along with the other currencies already supported.

I'd be happy to try implement it myself if I can have some guidance on where to look.

**Comment by knutnyg** [comment]
I see Zap relies on blockchains.info's currency api. There is no NOK there. Is it overkill to add a separate API call to fetch other currencies?

**Comment by ottosuess** [comment]
The current approach can definitely be improved.

Actually I would like to add an other API call. Relying on just one feels a bit fragile.
Perfect solution would be to query multiple sources and use an average of the results in the app.

**Comment by knutnyg** [comment]
Perfect. I'll look into it! 🚀

**Comment by ts95** [comment]
This issue can be closed since this was resolved in this PR https://github.com/LN-Zap/zap-iOS/pull/114. I'm personally using NOK in the app 🙂
