### ISSUE TITLE
Manage Channels channel list not updating

### ISSUE THREAD

**Issue by grantwest** [LN-Zap/zap-iOS#107]
**Describe the bug**
I opened a channel from my lncli and it does not show up in the list of channels on the Manage Channel page unless I restart the Zap app. 

**To Reproduce**
1. Start the Zap app and connect to your LND node
2. Use `lncli openchannel <pub_key> <# sats> 0`
3. Open the already running Zap app and Settings -> Manage Channels
4. The newly opened channel is not in the list
5. Restart the app, and now the channel is in the list.

**Expected behavior**
The new channel should be in the list the first time you navigate to Manage Channels after the channel is opened.

**Your environment**
- Device: iPhoneXS
- OS: iOS
- Version 12.1.4

**Comment by giulnz** [comment]
As i see in my test channels are not real time updated in "Manage channals" page. So as you, i need to restart or re-select wallet in "manage wallets" page.

**Comment by giulnz** [comment]
with the last release seems to work pretty good.

**Comment by ottosuess** [comment]
cool, closing this issue 🔥
