### ISSUE TITLE
add custom label for wallets in addition to the automatic labeling

### ISSUE THREAD

**Issue by ottosuess** [LN-Zap/zap-iOS#108]

**Comment by giulnz** [comment]
do you mean something like add tag/label to history for better organization ?
I will be great improve history section like other money map app, but it maybe will create a lack of privacy so maybe is better to separete from basic zap app and just give an history export tool ?

**Comment by ottosuess** [comment]
you can switch between multiple lnd nodes / wallets from your zap iOS app.

this issue is about labeling those different lnd nodes. basically overwriting their alias.

**Comment by giulnz** [comment]
Ah ok, i misunderstanding.
IMHOi don't think it's necessary, why not just change the Alias in conf file ? 
However a way can be Add "custom Alias" when you add remote node the first time (01.jpg)
and maybe let edit the node (02.jpg) so return to 01.jpg.
Also i think "edit" in 03.jpg is not necessary and redundant.

![01](https://user-images.githubusercontent.com/21366178/54926212-20362080-4f10-11e9-9665-7c686886c8b9.jpg)
![02](https://user-images.githubusercontent.com/21366178/54926213-20362080-4f10-11e9-970b-5476f2428a18.jpg)
![03](https://user-images.githubusercontent.com/21366178/54926215-20ceb700-4f10-11e9-9b7c-f17e24ca09d8.jpg)

**Comment by feitsau** [comment]
In my case I have 2 connections to the same lnd node because one is with local IP address (for use when I am at home) and one with external IP address (so I can also use it outside local network). 
Problem right now is that they have the same Alias so I never know which one is which. I custom label or the possibility to modify it would be great.

**Comment by ottosuess** [comment]
as a first step i can also show the node's ip in the wallet list.
