### ISSUE TITLE
Feedback on successful payment

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#115]
Curious everyone's opinion, but recently when watching people use Zap iOS (like in China), the payments happen so fast and this experience is so new that everyone asks if it just worked or what just happened when the app exits and re-renders the animated graph thing. I think maybe a success UI giving the user some feedback would be helpful and sexier. Maybe it goes away by default after 3 seconds or something so it doesn't require the user an extra click? Not sure. Looking in Zeplin it looks like we have these ideas:

<img width="376" alt="asd" src="https://user-images.githubusercontent.com/4040039/54540747-89dd8a00-4966-11e9-87d9-b43e75e17f87.png">

**Comment by ottosuess** [comment]
maybe add a cool full screen transition where the whole screen turns green.

**Comment by JimmyMow** [comment]
@ottosuess yeah that would be cool. just some feedback so the user knows it "worked"
