### ISSUE TITLE
Improving Wallets mini-modal

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#116]
I think the Zap iOS mini modal when holding down the Wallet icon can be improved a little.

1. I think the header section should have a different shade color to make the modal pop a little. Maybe we can do this with all of our mini models (like payment detail for example). This way the content doesn't just blend all together, there is a sense of hierarchy and structure to the data. See the Twitter one for an example:

![t-s](https://user-images.githubusercontent.com/4040039/54540863-c0b3a000-4966-11e9-8ad1-a094e82f8940.png)

2. Can we add Create new wallet and/or Connect to a new node to the mini-modal? To create a new wallet you must go through the settings currently. Would be cool if you can do it from the mini modal

3. Can I delete a wallet form the mini-modal? Twitter accomplishes this through an edit button that introduces a new UI. Unclear whether this is the best but something like this would be cool:

![dfd](https://user-images.githubusercontent.com/4040039/54540909-d2954300-4966-11e9-94f2-18ba9892589c.png)

**Comment by ottosuess** [comment]
1. I feel like the flat design is a bit more modern. (for example apple maps does it like that. without a header). But I also don't mind changing the design.
2. sure. any thoughts about the wording? "Manage Wallets"? Or should we have separate "Create" and "Add"?
3. The edit thing is apples default UI that you get for free. Adding that wouldn't take too long

**Comment by ottosuess** [comment]
![Simulator Screen Shot - iPhone XS - 2019-03-20 at 14 28 46](https://user-images.githubusercontent.com/37940680/54687738-31e48600-4b14-11e9-94da-312bd0322c68.png)
![Simulator Screen Shot - iPhone XS - 2019-03-20 at 14 28 43](https://user-images.githubusercontent.com/37940680/54687739-31e48600-4b14-11e9-93b1-b3a9e4c4399c.png)

just used our default ui elements here. all good? do I need to change something?
@ole1220 @JimmyMow

**Comment by ole1220** [comment]
looks nice :)
did you try to use the to switch colours for background/header? i think having using the lighter blue colour for the header would match better with the rest of the design.

**Comment by ottosuess** [comment]
<img width="458" alt="Screenshot 2019-03-20 at 15 00 45" src="https://user-images.githubusercontent.com/37940680/54691038-8428a580-4b1a-11e9-90d2-80422e4178ae.png">

@JimmyMow 👆 that's the design I merged

**Comment by ole1220** [comment]
👍

**Comment by JimmyMow** [comment]
👌
