### ISSUE TITLE
Suggested channels UI and/or Lapp browser UI

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#117]
I was using Facebook and came across this UI on my iPhone that I really love. Somehow it accomplishes header art, a title, description and 12 actionable profiles that each have an img, title and description.

I think this UI can be really helpful for suggested nodes in iOS or a Lapp browser where these are all services you can browse within a Zap browser. Hopefully, the below screenshot is enough to get the idea but will post sketches if needed.

![fb](https://user-images.githubusercontent.com/4040039/54540996-fb1d3d00-4966-11e9-830a-965b404a22ca.jpeg)

**Comment by ottosuess** [comment]
I like that. suggested nodes would be cool.
Right now when you tap the "+" button in the channel list the first thing that comes up is the camera.

Whats more important? Camera for scanning Node QRCodes or Suggested Nodes?
I'd emphasize the camera. If eveybody just blindly created a channel to one of the suggested nodes network topology would be worse than in the case where everybody created channels to custom picked nodes.

Maybe we can also combine the camera screen with the suggested node screen? like overlaying some of the circles over the live camera view. or have a card overlay like in apple maps that contains the suggested nodes.

**Comment by JimmyMow** [comment]
Yeah. We can also just have a suggested nodes button that takes you to this screen that you get to from the Add Channel camera

**Comment by JimmyMow** [comment]
Also, what is your opinion on having services like Yalls hosted there and if clicked we launch a web view with easy access to using LN on the web?

**Comment by ottosuess** [comment]
I'm not against a lap browser, but I also agree with this tweet:
https://twitter.com/mariodian/status/1101485268907913216

> Perhaps a dedicated app for those that really want this feature would make more sense. I think the wallet should be kept simple with as minimum attack vectors as possible.

Building a lap browser adds complexity and more code that needs to be maintained.

Is this really something the users need and will use on a mobile device?

**Comment by JimmyMow** [comment]
Yeah, that's a good point. I have similar thoughts with a Zap encrypted messaging app that has payments inside natively. I'm not entirely sure. I would assume Lapp browsers are not really used widely on mobile. But maybe some more user research and stuff would be better on our end
