### ISSUE TITLE
Sometimes zap ask for a new PIN

### ISSUE THREAD

**Issue by giulnz** [LN-Zap/zap-iOS#123]
**Describe the bug**
The PIN is set, but sometimes it ask me to set a new pin, and if i do it set the new pin without ask for the old. So basically you can take control of the wallet.

**To Reproduce**
i don't really understand when it happens, but since my experince in a month every day use, it happens 4-5 times, and as i remember never in the fist start, always when i put the app in backgound and re-open from background. 

**Expected behavior**
not to happen

**Screenshots**
![8ca95794-e1e3-4d0a-bec3-bd84c05376f8](https://user-images.githubusercontent.com/21366178/54816730-4b610b80-4c95-11e9-8cfe-6a66c4f1c830.jpg)

**Your environment**
- Device: Iphone X 
- OS: Ios 12.1.4
- Zap ios Version: 0.1.0 build 36

**Comment by ottosuess** [comment]
did this happen in build 36? I was hoping I fixed that issue by now.

**Comment by giulnz** [comment]
yes it happen 4 times this morning, and probably i find out :
- i open the app
- unlock
- turn off screen without exit the app
- wait 10 min
- unlock iphone
- it enter in zap app and ask for pin 
- put the right pin
- it ask for a new pin

**Comment by ottosuess** [comment]
thanks for reporting. i thought i fixed the issue before.

uploading a new alpha right now that should fix the issue.

**Comment by giulnz** [comment]
i upgrade test a bit and seems works.
