### ISSUE TITLE
See wallet balance when you are adding a new channel

### ISSUE THREAD

**Issue by giulnz** [LN-Zap/zap-iOS#124]
**Is your feature request related to a problem? Please describe.**
when i try to open a channel i never remember how much satoshi i have in wallet balance.

**Describe the solution you'd like**
see somewhere the wallet balance (in the last step as screenshot attached)

![newchannel](https://user-images.githubusercontent.com/21366178/54820086-3c328b80-4c9e-11e9-9625-fb18b727105a.jpg)

**Comment by ottosuess** [comment]
yes. we need that! 🙌
