### ISSUE TITLE
add Language in setting

### ISSUE THREAD

**Issue by giulnz** [LN-Zap/zap-iOS#132]
I think it is good that language is auto set as iphone language, but maybe people want to change it.
Personally I need to switch from english to italian only to check the translation so it's not very important.
Also becouse anyone can make the trasactions maybe some of it are bad and there is no way to set default english.

**Comment by giulnz** [comment]
Ok it's not important and not good for the semplicity goal of the project but someone need to monitor the comment request in https://crowdin.com/project/zap-ios

**Comment by ottosuess** [comment]
yo, sorry for the late reply 😀

changing languages based on system language is **very** simple. adding a language switch requires some work and complicates things. So thats not something i want to spend a lot of time on right now.

But i'll take a look at the comment requests later 🤞

**Comment by giulnz** [comment]
you're doing super work with other improvement, also i test italian language and it's good. So no problem.

**Comment by ottosuess** [comment]
i think i went through all the comments. if you have any more questions just hit me up anywhere or create an *issue* in crowdin. (i don't think its possible to subscribe to regular comments)
