### ISSUE TITLE
Show node nickname in channel form if we know it

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#135]
When using the new suggested channels, when clicking a node the form shows me the node displayed in `pubkey@host` format. If we know some name for this node, we should display it instead of the IP, giving a better user experience.

![Image from iOS](https://user-images.githubusercontent.com/4040039/56137950-728cbf00-5f5b-11e9-84e0-5a58da8b87e7.png)

**Comment by giulnz** [comment]
you mean the Alias, Yes probably you are right about UX but if you want to manual check you need that visualization format. Maybe ip is useless and so just replace Ip part with alias and leave Uri as manual check ?

**Comment by ottosuess** [comment]
sounds good. i'll replace the ip by alias 🙌
