### ISSUE TITLE
Some random consideration 

### ISSUE THREAD

**Issue by giulnz** [LN-Zap/zap-iOS#139]
1- (i don't know if is a problem of my node) in all my lightning payment, i never see fee preview. So actually it's just usuless :( 
But i don't think we can do a lot about it.
![photo5893326263127486531](https://user-images.githubusercontent.com/21366178/56376869-4e560a00-6209-11e9-9883-63fba28df96a.png)

2- I think will be nice when you click on a qr code to copy the string to clipboard.
![photo5893326263127486526](https://user-images.githubusercontent.com/21366178/56376871-531abe00-6209-11e9-9b15-437fc4515f18.png)
![photo5893326263127486527](https://user-images.githubusercontent.com/21366178/56376872-531abe00-6209-11e9-85e3-96b046390ee4.png)

If you ever will put an enable button in setting for exper users, an exper mode with :
3- can set on-chain transaction fees (https://github.com/LN-Zap/zap-iOS/issues/54)
4- can set public or private when open a channel 
5- can set sat_per_byte when openchannel
6- can set sat_per_byte when closechannel (cooperative)

**Comment by ottosuess** [comment]
some very good points! 🙌

can you create single issues for each of your points? (except 3 because there already is one for that)
they don't have to be super detailed, it just makes prioritisation and organisation simpler if we keep issues focused on a single item.

**Comment by giulnz** [comment]
Ok
