### ISSUE TITLE
Add more info in payment details

### ISSUE THREAD

**Issue by giulnz** [LN-Zap/zap-iOS#142]
First, in the movement details, received payments have memo but send payment not. Is there a motivation? 

Anyway i find out that some service/website use Proof of payment to manage session, especially if you lost cookie. 

![photo5929496811247087494](https://user-images.githubusercontent.com/21366178/56968083-cce46d00-6b62-11e9-8f49-3a04637fb733.png)

i think it's a standard way and more services will do it but i don't really go deep in that and i appreciate if someone have different opinion.
But acctually in Zap, if you send a payment you can't see the memo nor the preimage.
Also I don't think it will fit in the size, but the important thing is that will be copyable. 

My request is to add memo and preimage in the send payment movement details and if you click on it, it will be copied in iphone clipboard (one by one)

![photo5929496811247087493](https://user-images.githubusercontent.com/21366178/56968094-d241b780-6b62-11e9-80da-f932d9a4a6b6.png)

**Comment by ottosuess** [comment]
lnd does not give me the memo for the sent payment. but there already is an issue for that on lnd's side. (https://github.com/lightningnetwork/lnd/issues/2420) when this gets resolved i'll display the memo in the app.

preimage + copy function is a good point. will add that asap :)
