### ISSUE TITLE
Android?

### ISSUE THREAD

**Issue by P0u1us** [LN-Zap/zap-iOS#155]
I have been extensively seeking the forums and internet, but could not find any ref, therefor my Q here:
Hi, as an happy user of Zap desktop, and a strong opposer of any Apple product:
are there any plans to provide an android based wallet?

**Comment by ottosuess** [comment]
Yes, there will be an android wallet, but that is super secret 🤫😀

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
