### ISSUE TITLE
Access camera settings when scanning a QR-Code.

### ISSUE THREAD

**Issue by ChoynaMan** [LN-Zap/zap-iOS#156]
When attempting to scan a QR-Code to connect to my node, the camera preview area is blank. It's an easy get around by navigating to the Zap settings and enabling camera. But it would be nice to have the pop-up within the app asking if you'd like to access camera with this app. Thanks!

**Comment by ottosuess** [comment]
the popup should already be there. 🤔
but you only get it when you first try to access the camera.

**Comment by ottosuess** [comment]
deleted the app, made a fresh install and got the alert in the app to allow camera access. closing this now 🙌
