### ISSUE TITLE
After add a mobile node it stuck in loading

### ISSUE THREAD

**Issue by giulnz** [LN-Zap/zap-iOS#157]
Don’t know if it’s correlate to mobile wallet, I have my own node and today I create a new wallet in mobile to test it, I send some bitcoin from testnet faucet and received with confirm. I manually open a channel and after close app. After some hours I was no more able to access zap.
I also try to reboot iOS. Nothing change. I also wait 4 minutes but it stuck like attachment image 
![CA3874C3-55AF-4166-AF85-EA795722E38A](https://user-images.githubusercontent.com/21366178/57198611-1246d700-6f75-11e9-84a5-0257f9438b50.png)
That’s something similar to what happened with my test on Lightning lab iOS app

Also logs when I had access doesn’t work.

**Comment by giulnz** [comment]
Solved by downgrade to 0.3, delete mobile node, and upgrade to last.

**Comment by walletofsatoshi** [comment]
Working now
