### ISSUE TITLE
Syncing screen % stays at 0 no matter what

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#16]
### Background
When connecting to a new LND node syncing the syncing screen shows 0% no matter what block height my node is at

![image from ios](https://user-images.githubusercontent.com/4040039/43918902-165d5e96-9bda-11e8-8d08-dc90ba8e764e.png)

### Your environment
Bitcoin testnet
BTCD full node
LND full node

* version of Zap
Zap 0.1.0
* which version of iOS are you using
iOS 11.4.1

### Steps to reproduce
Connect a node that is in the middle of syncing

### Expected behaviour

The syncing screen should show accurate % throughout the syncing process

### Actual behaviour

Stays at 0%

**Comment by willcl-ark** [comment]
I can concur with this report using zap: 0.10, build: 14 and lnd: 0.5.1-beta

The date in the second line progresses through steps but the % does not move

**Comment by ottosuess** [comment]
@JimmyMow @mrfelton how do you calculate the percentage on zap desktop?
I'm only looking at `block_height` and not at `best_header_timestamp`.

That results in situations where block height is up to date but header timestamps still need to be synced.

**Comment by ottosuess** [comment]
nice. i'll just estimate the `lndCfilterHeight` assuming there will be a block every 10 minutes :)
