### ISSUE TITLE
Auto correct when recovering seed

### ISSUE THREAD

**Issue by cryptomulde** [LN-Zap/zap-iOS#162]
**Describe the bug**
The autocorrect in iOS is proposing the next seed words when recovering my seeds for several times. It learns more every time I retype the seeds it seems.

**To Reproduce**
1. start new wallet and recover
2. type existing seed
3. if you type seed several times autocorrect will "know" your seed and tell you the next words.

**Expected behavior**
Don't store any sensitive data.

If more information is needed I can clarify in more detail.

**Comment by giulnz** [comment]
I have same feeling and don’t know how really a problem is but yes I think it’s better to define this form as direct input don’t know if and how iOS manage this.

**Comment by ottosuess** [comment]
good feedback, thanks. 🙌

fixed
