### ISSUE TITLE
Total can receive count is wrong

### ISSUE THREAD

**Issue by giulnz** [LN-Zap/zap-iOS#164]
**Describe the bug**
If one or more channels go offline, the "total can receive" amount in channels page doesn't subctract remote amount

**Expected behavior**
subtract remote amount 

**Screenshots**
![5458701c-5b52-498e-a9a4-accba0b219f3](https://user-images.githubusercontent.com/21366178/57456301-803d1800-726d-11e9-92a7-4b5f70e6fa4a.png)
For example in this case total can receive should be 6.845.891

**Your environment**
- Device: iphonex
- OS: last
- Version 44

**Comment by ottosuess** [comment]
without you, nothing in this app would work at all 😅

thanks for reporting!

**Comment by giulnz** [comment]
😊 i would like to help you by code review but i'm not able so i just do my part with testing. also i like to do it (i do 1 year tester in a software company) so no problem.
