### ISSUE TITLE
Error: Too many private routes

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#182]
I am getting `too many private routes: 21` sometimes when I try and create an invoice

![image](https://user-images.githubusercontent.com/4040039/60637737-2f671d00-9de1-11e9-8a32-36665e5ad29c.png)

This node has 250+ channels, so I suspect that is the issue. Also, it seems here in this commit this may have been addressed: https://github.com/LN-Zap/zap-iOS/commit/a2e9538cb44b36796394f96c4d89fdfa7f6fd631#diff-c362da488d2ab9169badbfdad7459469L116

**Comment by ottosuess** [comment]
this error comes directly from lnd. lnd limits invoices to not contain more than 20 route hints, but seems to add more than that regardless:

(https://github.com/lightningnetwork/lnd/blob/aa1cd04dbf07a9195d5ada752f383988d8d01fa7/zpay32/invoice.go#L509)

**Comment by ottosuess** [comment]
maybe add an issue to the lnd github

**Comment by JimmyMow** [comment]
Ok, closing
