### ISSUE TITLE
Alpha: QR codes scanning and addresses pasting doesn't work

### ISSUE THREAD

**Issue by Jeiwan** [LN-Zap/zap-iOS#185]
**Describe the bug**
When QR code is scanned or address is pasted error pops up:
```
The operation couldn't be completed.
(Library.QRCodeScannerStrategyError error 0.)
```

The same error when pasting an address. I tried this address and its QR code:
```
lnbc20m1pvjluezhp58yjmdan79s6qqdhdzgynm4zwqd5d7xmw5fk98klysy043l2ahrqspp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqfppqw508d6qejxtdg4y5r3zarvary0c5xw7kepvrhrm9s57hejg0p662ur5j5cr03890fa7k2pypgttmh4897d3raaq85a293e9jpuqwl0rnfuwzam7yr8e690nd2ypcq9hlkdwdvycqa0qza8
```

**To Reproduce**
1. Install Zap from TestFlight.
2. Connect to a node.
3. Tap 'Send' on the main screen.
4. Scan a QR code or paste an address.

**Expected behavior**
There's no error and I can proceed with payment.

**Your environment**
- Device: iPhone6
- OS: iOS 12.0
- Version: all available alpha versions (0.4.0 (48), 0.4.0 (46), 0.4.0 (43), 0.4.0 (41), 0.4.0 (39)). Production app works correctly.

**Comment by ottosuess** [comment]
the address is for mainnet, maybe you are on testnet or simnet?

if you're on the right network it 'should' work ;)
i pushed an update with better error messages.

**Comment by Jeiwan** [comment]
I tried different addresses, including testnet and simnet. When scanning address from a wrong network in the production app it fails with message "Wrong network", while in the alpha app it always fails with "Library.QRCodeScannerStrategyError error 0" no matter what network I use.

Invoice amount is greater than 0, and everything else seems correct. Payments via 'lncli' cause no errors.

Your latest update hasn't got to TestFlight. How long does it takes to get through?

**Comment by ottosuess** [comment]
oh, sorry. didn't upload to testflight yet. just github. might take a few days until the next testflight version.

i'll check that bug again.
