### ISSUE TITLE
Replace spinner loader with skeleton loading screen(s)

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#189]
Right now when a user is waiting (catching up on filters, fetching data from a remote node, etc) they are given this traditional loading screen UI.

![image](https://user-images.githubusercontent.com/4040039/61499408-b2b17280-a98c-11e9-9ac0-71167019e98c.png)

It would level up the UX a lot if we instead opted for the skeleton loading screen(s) we discussed on Slack/Github

**Comment by ottosuess** [comment]
do we have a complete design somewhere?

**Comment by JimmyMow** [comment]
Hmm, I'm not sure. I know there are desktop ones, but are there not any for iOS yet?
