### ISSUE TITLE
"Sent Payment" notification when opening a channel

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#193]
Wasn't sure if this should be a bug report or feature request.

When testing the Zap iOS mainnet alpha, I received some on-chain funds and opened a channel. After the channel's funding transaction was successfully broadcasted, my history showed that I had a `Payment Sent` notification:

![image](https://user-images.githubusercontent.com/4040039/61727445-fdd6d700-ad38-11e9-8c07-b1af66ae8136.png)

Looking at my Manage Channels screen I can see that the channel funding tx did seem to broadcast successfully and my channel is in a pending open state:

![image](https://user-images.githubusercontent.com/4040039/61727505-1ba43c00-ad39-11e9-9ca8-42fdec815a65.png)

I think the history item `Payment Sent` could be potentially scary and misleading to new users that aren't very technical. Instead, if possible, copy like `Channel Opened` would be much better. What do you think @ottosuess?

**Comment by ottosuess** [comment]
i agree. is there an easy way by now to detect if this TX was used to open a channel?

**Comment by JimmyMow** [comment]
@ottosuess we can compare the channel point against the transaction hash
