### ISSUE TITLE
Ability to export logs for neutrino clients

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#197]
I think it would be a handy feature to allow users to export their node logs to an email, text, etc. For the purpose of debugging and such. I don't think it is necessary for there to be a UI for the logs, as debugging on a phone is pretty ridiculous and the logs move so fast anyways, but being able to tell a user to email themselves the logs and drop it in Slack would be nice

**Comment by ottosuess** [comment]
go to "settings", "Show lnd Log", tap on the share button in top right. 🙃
does it work on mainnet?

**Comment by JimmyMow** [comment]
_facepalm_

Hah, my bad, totally missed that. However, seems as if I can't get my mainnet logs to load. Getting this blank screen:

![image](https://user-images.githubusercontent.com/4040039/61797504-23251d00-aded-11e9-974e-9da9e4cfa764.png)
