### ISSUE TITLE
Show closing transaction in closing channel modal

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#199]
Currently, when a user has a channel that is closing, the channel modal shows the funding transaction. This is due to an LND bug. This bug has since been fixed here: https://github.com/lightningnetwork/lnd/pull/1933

This feature should now be available in LND 0.7.1

![image](https://user-images.githubusercontent.com/4040039/61805514-8918a100-adfb-11e9-984a-92eea6a2b6ec.png)

![image](https://user-images.githubusercontent.com/4040039/61805522-8c139180-adfb-11e9-8c10-47e83cb50169.png)

**Comment by ottosuess** [comment]
so you want to show the closing tx for closing channels?
is this related to the PR?

**Comment by JimmyMow** [comment]
Yeah, the idea is that when a channel is closing it would be better to link to the channel closing transaction. At least for me personally, I just want to see when the closing transaction is gonna confirm :D

**Comment by ottosuess** [comment]
i'd just show both. funding tx might be still relevant.

**Comment by JimmyMow** [comment]
Sounds good to me 👍
