### ISSUE TITLE
(Mainnet neutrino): Suggested nodes images not populating

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#201]
Maybe an issue with the new endpoint for suggested nodes? cc @mrfelton 

![image](https://user-images.githubusercontent.com/4040039/61831768-7ec6c900-ae34-11e9-8b64-1e5c04ad513d.png)

**Comment by mrfelton** [comment]
I don't think so @JimmyMow . The API is up and serving as it should:

http://resources.zaphq.io/api/v1/suggested-nodes

Maybe the iOS app is expecting some special headers? Maybe a CORS issue?

**Comment by ottosuess** [comment]
apple hates http. i have to whitelist every domain that is using `http` instead of `https`.

i checked, and images are also working over https, do we just want to change the urls in the json?

**Comment by ottosuess** [comment]
@mrfelton https://github.com/LN-Zap/zap-resources/pull/2

don't know if this is enough or if there is any reason why we should not do this.

**Comment by ottosuess** [comment]
nice. now it's working. thanks @mrfelton 🙌
