### ISSUE TITLE
UI padding a bit off on channel view

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#206]
In my opinion, the bottom border to our channel header is a little tight. What do you think @ottosuess? Should we give some space there?

![image](https://user-images.githubusercontent.com/4040039/62237256-48d69700-b396-11e9-829d-b8fa43e9a10f.png)

**Comment by ottosuess** [comment]
how did you get there? did you close a channel?

**Comment by JimmyMow** [comment]
Yeah after a channel close
