### ISSUE TITLE
"Opened Channel" vs. "Open Channel"

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#211]
Super small nit.

Other copy in `history` uses past tense like `Payment received`. I think we should change `Open Channel` to `Opened Channel` for consistency.

![image](https://user-images.githubusercontent.com/4040039/62811546-b174f080-bac7-11e9-9c4c-421282efee7a.png)

**Comment by ottosuess** [comment]
good point.

if you want to get some iOS commits you can edit all the copy yourself.
just edit this file: https://github.com/LN-Zap/zap-iOS/blob/master/Library/en.lproj/Localizable.strings#L252
