### ISSUE TITLE
Wrong balance after closing a channel

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#215]
When I closed a channel my home balance was super inflated. It seems the app accounted for my newly pending balance in my closing channel, but also counted the old balance as well? It seems to be my prior balance + my channel that just closed.

**Comment by ottosuess** [comment]
that's an issue with the limbo balance 😵

was it neutrino or were you connected to a full node?

**Comment by JimmyMow** [comment]
Neutrino.

I think this is an old LND bug that was fixed with 0.7.1. My channel was stuck in `Waiting close`, that was the issue. After a while, it fixed itself. Maybe we use this issue to track updating to LND 0.7.1?
