### ISSUE TITLE
BTC Address not found?

### ISSUE THREAD

**Issue by Deekee62** [LN-Zap/zap-iOS#216]
Hello,

sorry, for bothering you all, as this is most probably not a bug!

I'm still a newbie in this field and have not much experience :-)

Here my question:

When I copy the BTC Address in my Zap-APP on my MacBook and pasted it into the search field of Blockchain.info it can not be found?

What am I doing wrong?

Many thanks in advance for any hint.

:-)

**Comment by ottosuess** [comment]
which address are you copying?

**Comment by Deekee62** [comment]
bc1qu3c50qxpky4cp56twvyh28c5wvrww6exse5lm9

as copy from here:

![image](https://user-images.githubusercontent.com/33904339/63029774-6be26a00-beb1-11e9-8bc6-e1d3ec511d9a.png)

**Comment by ottosuess** [comment]
that button generates a **new** address for you. i think you get a new address every time you click on that button.
block explorers wont know anything about that address, because it is fresh and nobody sent bitcoin to that address yet.

if you have more questions you can ask at the repository for the desktop app directly (this is for the iOS app): https://github.com/LN-Zap/zap-desktop

**Comment by JimmyMow** [comment]
Hey @Deekee62. Zap does not create a new address every time that is clicked as that would inflate your wallet.

The reason you can't find anything on `blockchain.info` is that they don't support segwit/bech32 addresses which is what Zap uses by default. If you were to use Blockstream's block explorer, for example, you will find it no problem:

https://blockstream.info/address/bc1qu3c50qxpky4cp56twvyh28c5wvrww6exse5lm9

I personally would not suggest using any Blockchain.info services, they are years behind in Bitcoin development.

If you have any other questions feel free to open an issue in the Zap Desktop repository as @ottosuess said

**Comment by Deekee62** [comment]
Thanks for your reply, but unfortunately I can't find anything using that link neither!

**Comment by JimmyMow** [comment]
If you paste your address into the search form here? https://blockstream.info/

What address are you searching for? I was able to find your address pasted above

**Comment by Deekee62** [comment]
That's all I get, 0 transactions...

https://blockstream.info/address/bc1qu3c50qxpky4cp56twvyh28c5wvrww6exse5lm9
![image](https://user-images.githubusercontent.com/33904339/63037910-59236180-bec0-11e9-8405-79332a7fffd9.png)

**Comment by JimmyMow** [comment]
What are you expecting to see? Have you sent BTC to that address?

**Comment by Deekee62** [comment]
I thought that I could retrieve my balances of my BTC/LND node and add this address to my tracking software...
