### ISSUE TITLE
Recurring opened channel notification

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#217]
I keep getting the same opened channel notification for the one channel I opened. I assume it has something to do with the notification logic or LND firing too many callbacks or something?

**Comment by ottosuess** [comment]
![Screenshot 2019-08-16 at 10 07 18](https://user-images.githubusercontent.com/37940680/63153074-b8db5300-c00d-11e9-9c67-7c8b220ce063.png)
are you talking about this thing always showing the "new" tag?

**Comment by ottosuess** [comment]
the problem here is that **pending channels** don't have any information about when they have been opened. so i just take the current date and time. and thats why the events always show up as new.

any suggestions how to handle this?

**Comment by ottosuess** [comment]
i could search for the funding tx in the transaction list and get it's time_stamp 🤯

**Comment by ottosuess** [comment]
closed by 1707f6610c2e7e7ee35a272186dd1d5dd4c21580
