### ISSUE TITLE
Open channel empty state UI on home screen

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#219]
I wonder if we should put the channel empty state (where we suggest a user opens a channel) on the home screen where the deposit UI is once a user has deposited funds but they are all on-chain. 

If they wanna remain using zap as an on-chain only wallet that’s ok, they can close it. But I think after a user gets a conf this would be helpful, as now they have to find the channel management section in the settings.

Thoughts @ottosuess?

**Comment by ottosuess** [comment]
sounds good to me 👍

**Comment by ottosuess** [comment]
only question is how to do it.

imo we should not hide the send / receive buttons like with the "fund your wallet" empty state.
so where do we put the empty state? @ole1220 

![Screenshot 2019-08-19 at 15 47 39](https://user-images.githubusercontent.com/37940680/63270608-d1ab6900-c298-11e9-8371-324642c4afdf.png)
![Screenshot 2019-08-19 at 15 47 14](https://user-images.githubusercontent.com/37940680/63270614-d40dc300-c298-11e9-80f7-f841eb232c5b.png)

**Comment by chitowncrispy** [comment]
I believe @ottosuess is working on a redesign of the tab bar in the app. Do we still want to implement something like this given the redesign?

**Comment by ottosuess** [comment]
yes, we still need something like this. but still need a design (ping @ole1220)
