### ISSUE TITLE
Preset 100% of on-chain funds in open channel form

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#221]
For the empty state channels UI/UX, I think there should be a `just open a channel for me` option. Right now, we have the following UX when a user has funds, but they are all on-chain:

```
Open a channel

You can't transact on the Lightning Network yet! Let's open a channel to start transacting on the Lightning Network.

Open a channel (Button)
```

I think there should be another action item button that allows the user to elect Zap to just open a channel for them. My suggestion would be for Zap to open a channel for them to the Zap technologies node:

```
03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735
```

The only outstanding question is UI/UX for this feature. In particular: how much of the user's on-chain balance would we use to open a channel for them? Do we just default to 100%, or do we have a step in the process where we let them decide with a slider or something?

What do you think @ottosuess?

**Comment by ottosuess** [comment]
i like the idea, but the funding_amount issue is a tough UX question.

right now the 'open channel' button on the empty state opens the regular open channel flow where you 1. scan or select one of the recommended peers and 2. enter the amount.

the new button has to make the process much easier to be worth having it on the screen. i don't think skipping step 1 from the flow described above is a big enough improvement.

having big channels is better than having small ones. so going with 100% might be a good default?

(we also have to decide what funding_amount to suggest users on the regular open channel flow)

**Comment by JimmyMow** [comment]
Yeah, nice logic @ottosuess. I agree. I'll update the title of this issue to change the suggested input value to 100% when opening a channel through the empty state UI
