### ISSUE TITLE
Docs for simnet dev environment

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#224]
I'd like to do some development with Zap iOS and the simnet script to simplify LND on device dev. It would be nice if we put together some documentation on how to get that set up and running

**Comment by ottosuess** [comment]
we would need to pass the simnet btcd neutrino node to the app and run lnd in simnet mode on device. thats not super simple and would need some new UI.

in zap iOS **on device** and **remote** connections are very similar.
both use the same grpc interface and all that code is generated form the proto file.

testing remote connections is much simpler and shouldn't be different to testing on device lnd.
