### ISSUE TITLE
can’t tell what I am connected to

### ISSUE THREAD

**Issue by dmidnight** [LN-Zap/zap-iOS#254]
Installed latest build from testflight, wrote down 24 words, and opened into a default wallet. can see lnd log, but can’t tell which node i am connected to.

Is it a shared custodial service like lndhub?

**Comment by ottosuess** [comment]
the app is noncustodial. the node (lnd) is running on your phone.

**Comment by dmidnight** [comment]
Wow! That almost seems too good to be true. I had read the medium article and the Github README but I still didn't catch that.

I'd love to read more about this. Great work!
