### ISSUE TITLE
Give the option to choose type of coin used

### ISSUE THREAD

**Issue by homiee** [LN-Zap/zap-iOS#259]
So I set up LND with litecoind and I’m running my own Litecoin lightning network node.

I’ve synced the Zap iOS app to my node and it works like a charm, besides the fact that instead of showing my balance in Litecoin, it shows in Bitcoin.

Any chance to add Litecoin support to the app?

Thanks.

**Comment by ottosuess** [comment]
sorry, we're not planning to add any other coins.
