### ISSUE TITLE
Non-localizable wallet types

### ISSUE THREAD

**Issue by sohomang** [LN-Zap/zap-iOS#260]
**Describe the bug**
These three strings aren't localizable on Crowdin: "Local Wallet", "Remote Wallet" and "local".

**To Reproduce**
Go to 'Manage Wallets'.

**Screenshots**
![IMG_0256](https://user-images.githubusercontent.com/28465517/65396928-ee612200-ddab-11e9-8b7d-08661913b3e0.jpeg)

**Comment by ottosuess** [comment]
🙌
