### ISSUE TITLE
Dark theme shows light component on iOS13

### ISSUE THREAD

**Issue by mariodian** [LN-Zap/zap-iOS#262]
**Describe the bug**
On history tab, the top part of the screen shows a light colored component instead of a dark one. 
I tried turning off the light and automatic mode in iOS settings but nothing changed. 

**Screenshots**
![UNADJUSTEDNONRAW_thumb_1013](https://user-images.githubusercontent.com/3636406/65658117-f1cd0580-e058-11e9-8766-699856877dca.jpg)

**Your environment**
- Device: iPhone 8
- OS: iOS 13.1
- Version 0.4.0 (from Testflight)

**Comment by ottosuess** [comment]
uh, that's an iOS 13 issue, i thought i already uploaded a fix.
uploading now. thanks for letting me know 🙌
