### ISSUE TITLE
Syncing to blockchain

### ISSUE THREAD

**Issue by wesleyjohn** [LN-Zap/zap-iOS#263]
Hi,

I created a lightning node on Digital Ocean and created the wallet on my i-Phone but it does not sync to the block chain. I am very sorry if this is not the forum to mention this problem but I am not sure where else to go.

Can someone please help

Regards
Wesley

**Comment by JimmyMow** [comment]
Hey Wesley.

You can download Zap iOS that comes with a Lightning node inside the app. All the syncing can be done on your phone. If you head over to https://www.zaphq.io/download/ and download our `Zap iOS / Mainnet / TestFlight` app, that will allow you to test this feature

**Comment by sexgudinnan** [comment]
I have download the Mainet but it is the same as testnet🤷🏻‍♀️
