### ISSUE TITLE
"For security reasons zap does not support invoices without a specified amount."

### ISSUE THREAD

**Issue by Z-and** [LN-Zap/zap-iOS#264]
This is my first time seeing this message. Came up when I tried sending funds to my tippin.me account. I've never had this issue in the past, assuming it came with the latest  0.4 update. How else can we pay these invoices?

**Comment by JimmyMow** [comment]
They aren't secure, and users can lose funds by sending these payments. We have made services like tippin.me aware, I honestly don't know why they haven't done anything about it.

You can read more about this here: https://twitter.com/ln_zap/status/1150817272212131841

We plan on enabling this feature again when it is secure to do so (sphinx payments). Until then, using that feature is not secure and not something we want to expose our users to

**Comment by Z-and** [comment]
> They aren't secure, and users can lose funds by sending these payments. We have made services like tippin.me aware, I honestly don't know why they haven't done anything about it.
> 
> You can read more about this here: https://twitter.com/ln_zap/status/1150817272212131841
> 
> We plan on enabling this feature again when it is secure to do so (sphinx payments). Until then, using that feature is not secure and not something we want to expose our users to

Ok thanks, appreciate the quick response
