### ISSUE TITLE
set `use_mission_control` when querying for routes

### ISSUE THREAD

**Issue by ottosuess** [LN-Zap/zap-iOS#275]
https://api.lightning.community/#queryroutes

> If set to true, edge probabilities from mission control will be used to get the optimal route.

**Comment by chitowncrispy** [comment]
Do we want to always set this to true or should the user be given the option?

**Comment by ottosuess** [comment]
imo that's so low level that we don't want to expose it to the user. just always use_mission_control when estimating fees.
