### ISSUE TITLE
"Touch ID for Zap" presented throughout app usage

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#28]
**Describe the bug**
I am presented "Touch ID for Zap" when not needed. Randomly it will pop up while I'm using the app, sending transactions, opening channels, etc.

**To Reproduce**
Scan a payreq QR code
Pay the payreq

**Expected behavior**
I should only have to touch ID to auth into my wallet or maybe also to confirm payment. But the payment went through already

**Screenshots**
![img_1517](https://user-images.githubusercontent.com/4040039/44541443-9307c080-a6cf-11e8-96c8-5dc5bde88576.jpeg)

**Your environment**
- Device: iPhone8
- OS: iOS 11.4.1

**Comment by ottosuess** [comment]
latest alpha? the thing i uploaded today?

**Comment by JimmyMow** [comment]
yeah

**Comment by ottosuess** [comment]
should be fixed by now ;)
