### ISSUE TITLE
Zap Desktop (Windows) Channel options missing on iOS application

### ISSUE THREAD

**Issue by KhimairaCrypto** [LN-Zap/zap-iOS#291]
**Describe the bug**
The Zap Desktop (Windows) provides a very handy feature to configure a new channel:
1) Fee (Slow, Medium, High)
2) Keep this channel private (on/off)

**Expected behavior**
Provide the same options as the Zap Desktop (Windows) and maybe More ;-)

**Screenshots**
![Capture](https://user-images.githubusercontent.com/36352470/67063936-3f4e1580-f1b4-11e9-999f-68c917309b45.JPG)

**Your environment**
- Device: iPad
- OS: iOS
- Version 13

**Comment by ottosuess** [comment]
we already have a pr (#179) for the fee selection and an issue for the privacy toggle (#241)
