### ISSUE TITLE
No QR code on new invoice 

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#302]
Not sure what’s happening, but I am not getting a QR code sometimes when creating an invoice. This is when creating a Lightning invoice and when using my large routing remote node which has been causing me issues generally
![DA453003-B127-4037-AAAB-2107A4FDAC06](https://user-images.githubusercontent.com/4040039/67627624-dfdbaf80-f81c-11e9-9321-e4d0b296a593.png)

**Comment by ottosuess** [comment]
native iOS QR Code generator couldn't handle you large invoices.
i set input correction to "Low" (makes more sense for an app anyway). with low input correction QR Codes work for your node
