### ISSUE TITLE
Wallet Balance: Show what is in Channels and On chain

### ISSUE THREAD

**Issue by lobsterpub** [LN-Zap/zap-iOS#32]
**Is your feature request related to a problem? Please describe.**
Currently there is no easy way to see how much of your wallet balance is in channels and how much is on chain.

**Describe the solution you'd like**
On the main wallet screen I'd like to see a breakdown of the total so that the user can see what is currently in channels and what is on the blockchain.

**Describe alternatives you've considered**
Basic Example of wallet balance screen:
1,000,000s
⚡ 500,000s
🔗 500,000s

**Comment by ottosuess** [comment]
yes, we have been thinking about how to do this.
Here is a very early design we have floating around:

![wallet_home_b](https://user-images.githubusercontent.com/37940680/44896684-55232180-acf9-11e8-8e99-6212373edc92.jpg)

**Comment by ottosuess** [comment]
we decided to not go that route and stay with one balance for now.

in the end mainstream users should not care about their lightning balance.
