### ISSUE TITLE
When closing a channel the wrong channel is removed from the UI. 

### ISSUE THREAD

**Issue by JWWeatherman** [LN-Zap/zap-iOS#33]
**Describe the bug**
When closing a channel the wrong channel is removed from the UI. 

**To Reproduce**
1. Open two channels with the same node.
2. Close channel A.
3. Notice that channel B is removed from the UI.
4. Close zap (force close on iPhone) and reopen.
5. Notice that channel B is the only one displaying (channel A did close correctly).

**Expected behavior**
Channel A should be removed from the UI.

**Screenshots**

**Your environment**
iPhone SE

**Comment by ottosuess** [comment]
should be solved by new alpha
