### ISSUE TITLE
Connecting Zap (iOS) to Raspiblitz over Tor fails after updating to LND 0.9.0

### ISSUE THREAD

**Issue by ghost** [LN-Zap/zap-iOS#333]
**Describe the bug**
Zap (iOS) won't connect to Raspiblitz over Tor anymore after updating LND to 0.9.0. Things tried:

- Restarted Tor
- Re-run lndconnect
- Reset TLSCerts + macaroons
- Reinstalled Zap on iPhone
- Deleted /tor/lnd_REST folder
- Tried connecting to openoms' test node (also 0.9.0) - same error

All to no avail. Connecting over LAN still works fine. When scanning a new lndconnect QR-code in Zap the error given is: _Could not connect to server (Unknown Error 1)_

**To Reproduce**
1. Have Raspiblitz v1.3, update to LND 0.9.0
2. Try connecting to Raspiblitz over Tor from Zap (iOS)

**Expected behavior**
Expected the wallet to open as usual.

**Your environment**
- Device: iPhone 8
- OS: iOS 13.3
- Zap: Mainnet (testflight) version 0.5.1 (2.3)

**Additional**
Connecting through Tor in the App store version of Zap provides a different error, see below.

**Comment by theotherside** [comment]
![image](https://user-images.githubusercontent.com/1767817/73107303-20ea6b00-3ec3-11ea-8331-6d27d93cb7ee.jpg)

**Comment by jrimbolt** [comment]
> ![image](https://user-images.githubusercontent.com/1767817/73107303-20ea6b00-3ec3-11ea-8331-6d27d93cb7ee.jpg)
This is the same error I get when trying to connect through Tor in the App store version of Zap.

**Comment by openoms** [comment]
Here is the guide used to connect Zap (iOS TestFlight) through Tor: https://github.com/openoms/bitcoin-tutorials/blob/master/Zap_to_RaspiBlitz_through_Tor.md 

This issue has been confirmed again with the scripted version running the latest lndconnect:
https://github.com/rootzoll/raspiblitz/blob/v1.4/home.admin/97addMobileWalletTor.sh

`lndconnect --host=$(sudo cat /mnt/hdd/tor/lnd_REST/hostname) --port=8080 --nocert`

**Comment by jrimbolt** [comment]
Could this be an issue with the new format of `GetInfo`?

**Comment by ketominer** [comment]
Confirmed by various nodl users after upgrading to lnd 0.9.0

**Comment by SeanSharpe** [comment]
Same TOR connection issues on myNode after updating to LND 0.9.0

**Comment by fifthedition** [comment]
I also have the same issue on myNode with LND 0.9.0 and also on raspiblitz

**Comment by rootzoll** [comment]
Still the same with LND 0.9.2 :(

![IMG_0002](https://user-images.githubusercontent.com/2472225/77194116-937b5f80-6a9c-11ea-9569-a230efa95a61.PNG)

**Comment by hermanlim** [comment]
Procedure to connect to TOR 1.6RC2 (LND 0.10.2-beta.rc4)

1. Quit Raspiblitz menu by pressing 'x' or CTRL-C

2. Obtain onion address for lndrest8080 to insert into /home/admin/.lnd/lnd.conf:
sudo cat /mnt/hdd/tor/lndrest8080/hostname

3. Open /home/admin/.lnd/lnd.conf for editing:
sudo pico /home/admin/.lnd/lnd.conf

4. Insert hostname from step 2 into lnd by adding additional line:
tlsextradomain=[ONION_ADDRESS_FROM_STEP_2.onion]

5. Regenerate TLS certificate by going back to raspiblitz menu
LNDCREDS
RESET then SYNC
Note: If you run into problems here, open another terminal window and start LND manually and another one to run lncli unlock - this will regenerate the required files.

6. Get the correct code to put into ZAP. Quit Raspiblitz menu by pressing 'x' or CTRL-C to run lndconnect from command line:
lndconnect --host=$(sudo cat /mnt/hdd/tor/lndrest8080/hostname) --port=8080 --nocert -j

7. Finally, paste the output from step 6 into ZAP.

Notes:
On Desktop Zap (Linux), I was able to connect just by pasting the result of:
lndconnect --host=$(sudo cat /mnt/hdd/tor/lndrpc10009/hostname) -j
This did not work for Zap iOS. I don't know why.

**Comment by openoms** [comment]
I believe this is solved now by the Zap dev team. Should be  closed of someone confirms on iOS.

**Comment by hugomd** [comment]
I'm using the latest version of Zap for iOS and no longer see any issues 👍🏻

**Comment by ottosuess** [comment]
❤️
