### ISSUE TITLE
Wallet won’t load on LTE

### ISSUE THREAD

**Issue by quantumx314** [LN-Zap/zap-iOS#336]
On iOS 13.3.1 Zap 0.5.1 (3.3), the wallet loads instantly on home wifi but doesn’t load when on LTE. 
![4FA66FE3-6BA3-43B4-BE3A-8A2854344A80](https://user-images.githubusercontent.com/60696279/74293675-7ae39100-4d09-11ea-82b2-91be35e38539.png)

**Comment by jrimbolt** [comment]
Are you trying to connect to your own node? If so, did you set up DynamicDNS or connection over Tor? Otherwise you won't be able to connect to your node from outside of your local network.

**Comment by quantumx314** [comment]
Yes, I connect to my own node (Nodl Dojo) and I auto-connect through tor.

**Comment by quantumx314** [comment]
I double checked and not sure why but my node was indeed only connected to Mainnet. It used to be on Tor work properly so not sure what happened. Problem solved. Thanks
