### ISSUE TITLE
When you have 2 black channels next to eachother in the UI it is hard to see that they are not one card

### ISSUE THREAD

**Issue by JWWeatherman** [LN-Zap/zap-iOS#34]
**Describe the bug**
Two black channel cards are indistinguishable. Maybe add some drop shadow or something, but since it is expected that this UX is going away this bug can probably be closed "won't fix."

**To Reproduce**
1. Open two channels with nodes using black as a color. 
2. Notice it is very hard to see what is going on.

**Expected behavior**
Two clearly visible cards.

**Your environment**
iPhone

**Comment by ottosuess** [comment]
yeah, i guess we'll have to simplify the channel ui again :)

**Comment by ottosuess** [comment]
new channel ui should solve this.
