### ISSUE TITLE
Hi. I am running RaspiBlitz and would like to connect my IOS Zap Wallet.  I am connecting to it via Putty from a  Windows 10 Machine. When I generate the QR code, it is too large for my screen, and the ctrl- control does not work to shrink the image. I have tried to use the zapconnect -j command, but I get bash- command not found.  I wonder if there is a different way to shrink the code or better instructions for running the zapconnect -j command.  Thanks in advance.

### ISSUE THREAD

**Issue by glensidecross** [LN-Zap/zap-iOS#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ottosuess** [comment]
sorry, i don't know anything about windows.

if `zapconnect` is working `zapconnect -j` should be working as well 🤔

**Comment by ottosuess** [comment]
i'm closing this now. if you have any more questions regarding this issue please reopen it. 👍
