### ISSUE TITLE
Fees should not be displayed as mBTC

### ISSUE THREAD

**Issue by fjahr** [LN-Zap/zap-iOS#37]
Fees in the Transaction Detail view are currently always 0,0 mBTC. There should be a lower denomination for the fees in order for the user to be able to see them.

**Comment by ottosuess** [comment]
somethimes lnd returns 0 fees for transactions. maybe its better to not show a fee at all in those cases to avoid confusion?

**Comment by fjahr** [comment]
I just assumed the fee was just a few satoshis so that it was rounded to 0 mBTC. When it is truely 0 I am not sure how to handle it best. 0 satoshi would be more clear to me that there were really no fees but then showing satoshis next to mBTC may also not be great because of the inconsistency. Maybe fall back to "free" if it is really 0 sat. But I am not sure which one of these I prefer myself to be honest.
