### ISSUE TITLE
Localize number and date formatting in english

### ISSUE THREAD

**Issue by fjahr** [LN-Zap/zap-iOS#38]
As an english user of the app I would expect the number formatting to be in english as well: the decimal separator should be a dot not a comma.

0,1 mBTC should be 0.1 mBTC

As a US user I would also expect the date formatting on the graph in the wallet screen to be formatted MM/DD/YYYY.

16.10.2018 should be 10/16/2018.

**Comment by fjahr** [comment]
True, my region is set to Germany, so if the formatting is conforming to that, then it works :)

**Comment by ottosuess** [comment]
👍
