### ISSUE TITLE
Cannot connect to remote node public IP

### ISSUE THREAD

**Issue by Ulmo** [LN-Zap/zap-iOS#42]
1. How safe is it to use Zap to connect to my LND server via public IP?
2. I can connect to my LND backend via its private LAN IP# (10.x.x.x address), make payment to invoice, etc., but when I try to my public IP# (confirmed port forwarded using tcpdump), it gives a failure error (with no further details) in Zap. The configuration from zapconnect doesn’t work unless I edit the IP address to be the internal (behind NAT) LAN ip#, which is always how I’ve (successfully) used Zap so far, but I want to make it more mobile now, obviously, so I can use it places other than home. I have the externalip set correctly in lnd.conf.

Any ideas? How do I debug this? I don’t see any log entries in lnd’s log file despite it having listening port and occasionally an open tcp connection that Zap says doesn’t work for it.

**Comment by resipsa2917** [comment]
I use a VPN.  I think it will be more secure than opening a port to LND and then you have the added benefit of access to your internal network from your phone.

I use Asuswrt-merlin on my router as the VPN server, and OpenVPN on my iPhone.  This way you can give Zap your internal IP address (no port forwarding) once you connect.  And it will be as secure as your VPN.  I use RSA 2048, SHA-512 and AES-256-CBC as that's the best I could get from OpenVPN on the iPhone.

Downside is that you have to connect to the VPN (in settings or OpenVPN) as I could not get the connect on demand to work.

**Comment by mrfelton** [comment]
> How safe is it to use Zap to connect to my LND server via public IP?

By default, when you use `zapconnect` to connect your mobile device to your lnd node, it will share the `admin.macaroon` with your mobile wallet. This macaroon has full admin rights over the node.

Exposing the gRPC interface to the internet does carry some risk, in that a user with access to that interface will be able to fully control the node if they have the correct macaroon (such as the admin macaroon that is now stored on your phone).

You can mitigate this risk by only sharing relevant macaroons with users that you trust, and revoking macaroons if you suspect they have been compromised.

@Ulmo you will need to add `tlsextraip ` and/or `tlsextradomain` to your `lnd.conf` (see https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L27-L33) and then regenerate your ssl certs before you can connect to it via it's external address.

**Comment by Ulmo** [comment]
MrFelton, thank you.  That worked perfectly.

Resipsa2917, that's the solution I was originally going to use theoretically, but I didn't know what programs to use.  I can start to look into VPN types that I could use.

**Comment by ottosuess** [comment]
right now it's not possible.

i've been playing around with tor the last few days. but running tor on iOS is hard.
I don't know if i'll ever get it to work, but i'm trying.
