### ISSUE TITLE
Failed to send

### ISSUE THREAD

**Issue by willweatherman** [LN-Zap/zap-iOS#44]
**Description**
When I try to send money to my buddy it fails to send.

**To Reproduce**
Buddys phone: click on Receive,
Lighting,
Enter 100sat,
Click on Next,
Generate Request.

My phone: Click on send,
Scan QR code,
Click send,
Enter passcode.
It endlessly says "sending...".

**Expected behavior**
Should send 100sat to my buddies wallet.

**Screenshots**
My buddies QR code

![img_0081](https://user-images.githubusercontent.com/44322947/48274644-c7a73080-e411-11e8-8874-34b64f1ec353.jpg)

My screen after I click send.

![img_0080](https://user-images.githubusercontent.com/44322947/48274648-cb3ab780-e411-11e8-85f6-aad6daa0c642.jpg)

**Your environment**
- software : zap ios
- devices : iphones
Me and my buddy both have channels to our hub/ipad

**Additional context**
I am talking to @mrfelton on slack and there seams to be a problem with the private tag in the invoices. And their missing routing hints.

**Comment by ottosuess** [comment]
yo, private flag looks to be correct.
the "expected fee: -" label indicates that lnd can't find a route to your buddies node.

I probably have to add an error message to show whats going on there.

**Comment by willweatherman** [comment]
Hey, I have a route from me to my hub/ipad and a route from my buddie to the hub/ipad. both routs work to the hub just not routing through the hub.

**Comment by ottosuess** [comment]
closing this because this bug is about lnd and not about the zap ios wallet.
