### ISSUE TITLE
Switch between saved Remote Node Configs

### ISSUE THREAD

**Issue by fjahr** [LN-Zap/zap-iOS#48]
This is certainly more of a power user feature but I think it would be really great if users could switch between different remote note configs that are saved in the app. This would allow to switch between testnet and mainnet nodes easily for example. Another use case could be users that have a business and want to switch between their business node and their private node.

So instead of just being able to reset the remote node config in the settings, there would be a management menu where I could add and remove remote node configs and activate one of them to be used in the rest of the app.

**Comment by ottosuess** [comment]
i like the idea. this would be great for power users.
i just don't want to make setup more complicated for our average users.

do you have an idea how to do this ux wise without adding more steps for regular users?

**Comment by fjahr** [comment]
I don't think there need to be any changes to the initial setup. I would just like to add additional remote node configurations without the need to reset the old one after I have configured the first one in the initial setup. Then I would like a possibility to switch between them but this could all be hidden in the settings in the place where the "Reset Remote Node Configuration" is. If a normal user only has one remote node she would probably not even notice that feature unless they need to change settings of their remote node, the way I think of it.

I roughly envisioned it like this:
- Initial setup for remote node config stays exactly the same
- In the settings list "Reset Remote Node Configuration" changes to "Manage Remote Nodes"
- "Manage Remote Nodes" leads to a list of all remote nodes that are already configured (just one in the beginning).
- It shows which remote node is currently actively used in the app. This can be switched.
- New remote nodes can be added, existing remote nodes can be removed
- If the last remote node is removed fall back to the behavior of "Reset Remote Node Configuration"

Does it make sense or am I missing something that needs to change in addition that regular users would notice?
