### ISSUE TITLE
Home page graph seems broken

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#49]
**Describe the bug**
My graph on the home page seems to be displaying inaccurate numbers

**Expected behavior**
Correct numbers :p

**Screenshots**
![image](https://user-images.githubusercontent.com/4040039/49096916-3fa69080-f231-11e8-85b1-8a18c253fb4d.png)

I do not have 0.8 BTC ^

**Additional context**
I've also been spending frequently but don't seem to have the line changing. I assume it's because the numbers on the right are off

**Comment by ottosuess** [comment]
fixed by a5ac548ee246c9eabaa3807f93db1c9282603175 😊
