### ISSUE TITLE
Incorrect balance reported

### ISSUE THREAD

**Issue by willcl-ark** [LN-Zap/zap-iOS#50]
Opening the Homepage shows an incorrect balance vs my lnd node which I am connected to. In this case the discrepancy is:
Zap: 10,253,348
lnd:    2,667,336

I am using Zap 0.1.0 build:14 on iOS 12.1 (16B92) on an iPhone X 256GB
with
lnd 0.5.1-beta on Intel NUC running Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-39-generic x86_64)

**Expected behavior**
Correct balance

**Screenshots**
![img_1305](https://user-images.githubusercontent.com/6606587/49254232-a047f000-f420-11e8-9b9a-d6795fb6d9f6.png)

**Comment by ottosuess** [comment]
The app is displaying `WalletBalance` + `ChannelBalance`.

What does your lnd return for those calls?

**Comment by willcl-ark** [comment]
@ottosuess that gives me exactly as shown in Zap! False alarm I guess then, sorry.
