### ISSUE TITLE
add blockstream.info to get current block height

### ISSUE THREAD

**Issue by ottosuess** [LN-Zap/zap-iOS#53]
api endpoint: https://blockstream.info/api/blocks/tip/height

**Comment by ottosuess** [comment]
not a label, we need the block height for estimating stuff like the sync percentage.
already using blockexplorer, btc.com and blockcypher apis for that.

https://github.com/LN-Zap/zap-iOS/blob/master/Lightning/Services/Misc/BlockChainHeightUpdater.swift

to be honest adding blockstream api would not really be an improvement. just an additional backup api in case the other 3 brake

**Comment by reez** [comment]
Ah, ok I see now, thanks for the context

**Comment by ottosuess** [comment]
closed by #72
