### ISSUE TITLE
Receive screen is cut off on iPhone SE

### ISSUE THREAD

**Issue by lobsterpub** [LN-Zap/zap-iOS#6]
### Background

On the receive screen I cannot see the amount I am entering, or any other info that might be there.

### Your environment

* Zap iOS Version 0.1.0
* iOS Version 11.4.1
* iPhone SE

### Steps to reproduce

Enter the app, click Receive

### Expected behaviour

Be able to see the amount I am entering. See screenshot:

![iphonese](https://user-images.githubusercontent.com/22959886/43354767-4712a47c-927c-11e8-9270-1e62cffbdd9b.jpg)

**Comment by ottosuess** [comment]
thanks for letting me know. should have tested this :)

**Comment by ottosuess** [comment]
we're working on a total redesign of the screen should be ready this week.

**Comment by ottosuess** [comment]
should be fixed by #24
