### ISSUE TITLE
Support connect via Tor

### ISSUE THREAD

**Issue by Empact** [LN-Zap/zap-iOS#62]
In #42 you mentioned you're looking into Tor support. This is meant to track that feature.

As of right now I'm getting "Could not connect to server", when the certificate and address are in place, the hidden service address is in the "Address" field, and lnd.conf has tlsextradomain set to the hidden service domain.

**Comment by ottosuess** [comment]
would definitely be cool. but running tor on iOS is not that easy.

**Comment by ottosuess** [comment]
i've tried setting up Tor with this framework: https://github.com/iCepa/Tor.framework

but that didn't really work.
another problem is to make the grpc library to run over Tor.

if you can come up with an example project that is connecting to lnd using grpc over tor that would be really helpful. :)

**Comment by seth586** [comment]
Orbot on android allows the Zeus app to connect to LND, but yeah I'm not aware of an iOS method.

**Comment by ketominer** [comment]
gRPC over tor is not a problem as long as it has its dedicated hidden service and the .onion address is added to the TLS cert of lnd using tlsextradomain=

**Comment by ottosuess** [comment]
The problem with gRPC is that the iCepa Tor framework is using `NSURLSession` api and the grpc library is using `CFStream` api.

**Comment by ketominer** [comment]
hmm seems it's designed for http only, probably not the good framework to use. Would need something generic TCP instead...

**Comment by Kixunil** [comment]
I completely agree with @ketominer. It seemed appropriate to open #368
