### ISSUE TITLE
Request: Confirm 'Closing of Channel' 

### ISSUE THREAD

**Issue by lobsterpub** [LN-Zap/zap-iOS#7]
### Background

On the channel information screen there is the 'Done' on the upper right, and 'Close' at the bottom.  I personally had a moment of confusion on which button will simply close the window, and accidentally closed a channel.

### Your environment

* Zap 0.1
* iOS 11.4.1

### Expected behaviour

I think either the UI needs some work or at least a window to confirm the user wants to close the channel.

### Actual behaviour

Clicking 'Close' immediately closes the channel.

**Comment by ottosuess** [comment]
good point. i'm currently working on a channel list redesign that gets rid of the done button.

you can already see a first draft here: https://twitter.com/ottosuess/status/1023941608079876096

**Comment by ottosuess** [comment]
should be fixed on current master
