### ISSUE TITLE
waitingCloseChannels are not displayed

### ISSUE THREAD

**Issue by ottosuess** [LN-Zap/zap-iOS#70]
**Describe the bug**
Lnd's `PendingChannels` result contains an array of `WaitingCloseChannel`s.
The Channels in this array should be displayed as closing channels on the channel screen in the app but right now they are ignored.

**To Reproduce**
Close a channel, call `lncli pendingchannels` you see the closed channel under `"waiting_close_channels": [` but not in the app.

**Expected behavior**
The channel should be displayed in the app with a "Closing" label.

**Additional context**
There is an extension of `LNDPendingChannelsResponse` that transforms all pending channels to `Channel` structs here: 
https://github.com/LN-Zap/zap-iOS/blob/master/SwiftLnd/Model/Channel.swift#L56

It might be enough to just do the same as with `pendingOpenChannelsArray`, `pendingClosingChannelsArray` & `pendingForceClosingChannelsArray `, just for the `waitingCloseChannelsArray`.

**Comment by knutnyg** [comment]
I did some initial testing. During debugging the RPC-call for `pendingChannels` returns an empty list even though lnd reports a waitingCloseChannel. I'll look a bit more into it.

**Comment by ottosuess** [comment]
i just made a breakpoint in the `extension LNDPendingChannelsResponse`'s `var channels: [Channel] {` and after force closing an offline channel i got a waitingCloseChannel.

```
(lldb) po waitingCloseChannelsArray
▿ Optional<NSMutableArray>
  ▿ some : 1 element
    - 0 : <LNDPendingChannelsResponse_WaitingCloseChannel 0x600003f9fe40>: {
    channel {
      remote_node_pub: "032f798001f0ff250386821997e6598aacbca0db6d403541eccbda29dd18b12d7f"
      channel_point: "3c360b61a5709a0eb16945bfa2fb33a0775d15ca0da80a4963d004d38ab99ccc:1"
      capacity: 14288813
      local_balance: 14288630
    }
    limbo_balance: 14288630
}
```

**Comment by knutnyg** [comment]
Strange. I'll look into it!
