### ISSUE TITLE
update Bond pod to 7.0.0

### ISSUE THREAD

**Issue by ottosuess** [LN-Zap/zap-iOS#73]
i'm using Bond to bind view models to ui elements https://github.com/DeclarativeHub/Bond.

some breaking changes regarding observable collections need to be fixed for the new Bond 7.0.0 release.

just run `pod update Bond` and take a look :)

**Comment by knutnyg** [comment]
Migration guide: https://github.com/DeclarativeHub/Bond/blob/master/Documentation/Migration.md
