### ISSUE TITLE
Request: Sending coins onchain

### ISSUE THREAD

**Issue by cidadededeus36** [LN-Zap/zap-iOS#8]
### Background

scanning normal onchain btc qr code crashes the app

### Your environment

Zap 0.1.0
iOS 11.4.1 on iPhone 7

### Steps to reproduce

scan btc qr code using send

### Expected behaviour

ability to send onchain from wallet or give error message

### Actual behaviour

crashes

**Comment by ottosuess** [comment]
i just tried sending on chain to different addresses and it worked. can you share the qr code or address?

**Comment by cidadededeus36** [comment]
I tried it on the wiki leaks donation address below... it simply crashes upon scanning. I've tried it with legacy addresses aswell...


![unknown](https://user-images.githubusercontent.com/11336029/43505503-04790d20-951c-11e8-9933-840799d26424.png)
36EEHh9ME3kU7AZ3rUxBCyKR5FhR3RbqVo

**Comment by cidadededeus36** [comment]
was this fixed? scanning the qr code above crashed the app on my end. i updated to the new layout released today. same result.

**Comment by ottosuess** [comment]
I fixed one crash related to that address. But maybe there is more. I'll check.
Thanks for letting me know! 👍
