### ISSUE TITLE
Zap 0.1.0 (24) - Why Back To Zap Connect???

### ISSUE THREAD

**Issue by resipsa2917** [LN-Zap/zap-iOS#81]
Why are we back to using zapconnect?

**Comment by resipsa2917** [comment]
Updated Zap-iOS, didn't xfer my previous settings, and now wants me to use zapconnect to re-connect.

**Comment by Jonbros01** [comment]
Same... how can I connect back to my LN node?

**Comment by andrerfneves** [comment]
Seems to be related: https://github.com/LN-Zap/lndconnect/issues/6
Having same issues

**Comment by ottosuess** [comment]
@resipsa2917 what did you use before to connect zap iOS? everything should still be working. lndconnect, zapconnect, BTCPay Server

**Comment by Jonbros01** [comment]
I have done it with node launcher,  it was integrated at that time but now Pierre removed it...

Last night I followed this guide and was able to make it work.

https://twitter.com/jonbros01/status/1095911066478002176?s=21


Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ottosuess** [comment]
@Jonbros01 nice, maybe open an issue for the node launcher? 😇
