### ISSUE TITLE
Allow unlocking remote LND

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-iOS#82]
It would be nice if Zap iOS allowed you to authenticate and unlock a locked LND instance. This is possible with the desktop application and I use Zap to unlock my LNDs all the time

**Comment by ottosuess** [comment]
ok. how are we doing this?
users have be able to enter a password and then tap on a button that says "Unlock".

Should we save the password?
Do we need a design?

**Comment by JimmyMow** [comment]
Yeah definitely needs design. I'd say no on saving the passwords. I'll give all of this some thought, I just wanted to document it in an issue so I didn't forget 😄
