### ISSUE TITLE
History doesn’t show any Payments Recieved

### ISSUE THREAD

**Issue by missaghi** [LN-Zap/zap-iOS#84]
**Describe the bug**
I received a payment and it showed up on ver 22 but not 24

**To Reproduce**
1. Click on history
2. Payment receipt missing, invoice says expired

**Expected behavior**
Payments recieved should appear in history

**Screenshots**

Ver 24 (payment recieved missing)
![ver 24](https://user-images.githubusercontent.com/550556/52903721-5ed90c80-31e7-11e9-8073-d3ac58ddb48e.jpeg)

Ver 22 (payment received appears)
![ver 22](https://user-images.githubusercontent.com/550556/52903736-79ab8100-31e7-11e9-9894-fd951b426962.jpeg)

**Your environment**
- Device: iPad Pro and iPhone
- OS: iOS 12

**Comment by missaghi** [comment]
Same on ver 25. love the multiple wallet storage! You guys are awesome!

**Comment by knutnyg** [comment]
+1 Experienced this bug in the wild yesterday. Even though lnd shows the invoice as settled, Zap doesn't catch up.

**Comment by ottosuess** [comment]
i just tried and could not reproduce. 😵

it worked both when i had the app running and closed when receiving (on testnet).
any hints on how to reproduce this?

**Comment by knutnyg** [comment]
1. I created a wallet on bluewallet
2. fund this wallet with a few sat
3. create an invoice in Zap and copy it to clipboard
4. pay invoice in bluewallet
5. Bluewallet list it as paid. LND list it as settled, Zap just shows it as created

Tested just now

**Comment by ottosuess** [comment]
ok, this is because of a new lnd version.

`invoice.settled` was deprecated and replaced by `invoice.state` at some point of time.
on older lnd versions `state` is returned as `open` even though the invoice has been settled.

```
(lldb) po invoice.state == .open
true
(lldb) po invoice.settled
true
```

i'll think about a solution 😭

**Comment by knutnyg** [comment]
I guess you have to check if the invoice has the settled field? And fallback to state?

**Comment by ottosuess** [comment]
right now invoices always have the `settled` field. it's just deprecated, hasn't been removed yet.
i could just keep using only that and ignore the issue until it gets removed.

or do some kind of api versioning.
