### ISSUE TITLE
New Nodesetup - App is spinning on Startup

### ISSUE THREAD

**Issue by CryptoSigmund** [LN-Zap/zap-iOS#85]
**Describe the bug**
Did some changes to the actual Node in the app, so new tls.cert and admin.macaroon is needed. After launch of the app, only the loading circle is spinning and never comes to an end.

**To Reproduce**
1. Go to 'app'
2. app loading circle spinning till infinity

**Expected behavior**
App should load.

**Screenshots**

**Your environment**
- Device: iPhone Xs 
- OS: 12.1.4
- Version 25

**Additional context**
App was running good before changes to the Node.

**Comment by JimmyMow** [comment]
@molxyz reported the same issue in LND slack

```
LND version: 0.5.2 release
Zap iOS version: 25
Reproduction steps:
     - Adjust node settings (in @molxyz case, change the node password)
     - Launch Zap, get the infinite spinner
```
