### ISSUE TITLE
Connect Remote Node - Paste feature

### ISSUE THREAD

**Issue by resipsa2917** [LN-Zap/zap-iOS#9]
What do I "Paste" to connect to my remote node in zap-iOS?  

I tried "zapconnect > temp" and then pasting "temp" in zap-iOS but no joy.

Would be easier to just paste the IP, macaroons, and tls manually.

**Comment by cidadededeus36** [comment]
I don't believe you can paste it... to my knowledge you can only edit the IP address after scanning the QR code.

**Comment by resipsa2917** [comment]
Thanks for the info.  

I'm on a headless Centos box.  SSH is my only access.  Suppose I can set up a VNC server on the box and install xwindows.

**Comment by ottosuess** [comment]
run `zapconnect -j` to get a JSON instead of a QR-code. you can then copy & paste the JSON in the app.
