### ISSUE TITLE
Make Zap iOS compatible with Tippin.me QR code

### ISSUE THREAD

**Issue by lobsterpub** [LN-Zap/zap-iOS#90]
**Is your feature request related to a problem? Please describe.**
The Zap iOS app doesn't recognize the qr code generated on tippin.me.

**Describe the solution you'd like**
Have the Zap iOS app be able to read the qr code on tippin.me

**Describe alternatives you've considered**
I am able to copy/paste the request into the zap app and send payment

**Additional context**
This might just be tippin.me not using the standard qr code colors (black/white) so might just be on their end 🤷‍♂️

**Comment by ottosuess** [comment]
thanks for letting me know. i'll take a look! 🤓

**Comment by ottosuess** [comment]
@JimmyMow and I checked, and for us scanning the qr code worked. 🤔

**Comment by ForgeLee** [comment]
still having this issue

**Comment by ForgeLee** [comment]
would be nice if it worked
